project:
  type: book

book:
  title: "R for Visual Analytics"
  author: "Dr. Kam Tin Seong"
  date: "12/4/2023"
  chapters:
    - index.qmd
    - part: "The Building Block"
      chapters: 
      - chap01.qmd
      - chap02.qmd
      - chap03.qmd
      - chap04.qmd
    - part: "Not So Common Chart"
      chapters:
      - chap05.qmd
      - chap06.qmd
      - chap07.qmd
      - chap08.qmd
    - part: "Visual Analytics"
      chapters:
      - chap09.qmd
      - chap10.qmd
      - chap11.qmd
      - chap12.qmd
    - part: "Visualising and Analysing Multivariate Data" 
      chapters:
      - chap13.qmd
      - chap14.qmd
      - chap15.qmd
      - chap16.qmd
    - part: "Visualising and Analysing Time-series Data"
      chapters:
      - chap17.qmd
      - chap18.qmd
      - chap19.qmd
      - chap20.qmd
    - part: "Visualising and Analysing Geographical Data"
      chapters:
      - chap21.qmd
      - chap22.qmd
      - chap23.qmd
      - chap24.qmd
    - part: "Visualising and Analysing Spatio-temporal Data"
      chapters:
      - chap25.qmd
      - chap26.qmd
    - part: "Visualising and Analysing Network Data"
      chapters:
      - chap27.qmd
      - chap28.qmd
    - part: "Visualising and Analysing Text Data"
      chapters:
      - chap29.qmd
      - chap30.qmd
    - part: "Information Dashboard Design with R"
      chapters:
      - chap31.qmd
      - chap32.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

